version: '3'
services:
  postgresql:
    image: postgres:13.2
    container_name: postgres-blog
    network_mode: bridge
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
      - TZ=Etc/UTC