[tool.isort]
    default_section = 'THIRDPARTY'
    known_django = 'django'
    src_paths = 'blog/'
    no_lines_before = 'LOCALFOLDER'
    skip = 'migrations'
    multi_line_output = 3
    include_trailing_comma = true
    use_parentheses = true
    honor_noqa = true
    # https://github.com/PyCQA/isort#custom-sections-and-ordering
    sections = ['FUTURE','STDLIB','DJANGO','THIRDPARTY','FIRSTPARTY','LOCALFOLDER']

[tool.pylint]
    [tool.pylint.master]
        ignore='CVS'
        jobs=1

    [tool.pylint.message_control]
        disable=['invalid-name',
                'missing-module-docstring',
                'missing-class-docstring',
                'missing-function-docstring'
                ]

    [tool.pylint.django_foreign_keys_referenced_by_strings]
        django-settings-module='mysite.settings'

    [tool.pylint.format]
        indent-after-paren=4
        indent-string='    '
        max-line-length=79

[tool.black]
    skip-string-normalization=true
    target-version=['py38']
    line-length=79
    exclude='/(\.git|\.venv|env|venv|build|dist)/'

[tool.pytest.ini_options]
    DJANGO_SETTINGS_MODULE='mysite.settings'
    addopts = '--strict-markers'